### ISSUE TITLE
Chararacter

### ISSUE THREAD

**Issue by CatsAreFluffy** [DJMcMayhem/Brain-Flak#74] opened 2017-06-04 18:14 UTC
https://tio.run/##SypKzMzTTctJzP7/Pzq22qa61q661iY61q72/39DSwVD4/@6KQA
See output

**Comment by 1000000000** [comment] 2017-06-04 22:49
Could you be a little more specific with what the problem/request is? I looked at the output and did not see anything off (besides the fact that it might be good idea to have it print `Stack empty` or some variation of that if the stack is empty).

**Comment by Wheatwizard** [comment] 2017-06-04 23:14
The problem is (I've actually know about this for a while) that `Character` is misspelled `Chararacter`.

[Here](https://tio.run/##SypKzMzTTctJzP4PBIaWCobG/3VTAA) is a test with less going on.  It occurs whenever `-d` is present.  Since this will be fixed later on here is the output when run in Brain-Flak 1.4.2 (current as of June 4th):
```
Cycles:
0
Program:

^
Chararacter 1
Stack:  
^
```

**Closed as completed** 2017-06-06 14:00 UTC
Labels: bug
